spring.application.name=hcm-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hcm_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Naruto123}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.bootstrap-admin.username=${APP_ADMIN_USERNAME:admin}
app.bootstrap-admin.password=${APP_ADMIN_INITIAL_PASSWORD:}
app.jwt.secret=${JWT_SECRET:}
